[pytest]
# Carpeta donde Pytest busca los tests
testpaths = tests
# Permite importar "utils" desde cualquier test
pythonpath = .

# Muestra los logs en la consola mientras corren los tests
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %H:%M:%S

# Además guarda los logs de la ejecución en un archivo
log_file = reports/ejecucion.log
log_file_level = INFO
log_file_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
